name: Copilot Setup Steps

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'package-lock.json'
      - '.github/copilot-config.json'
  pull_request:
    branches:
      - main
    paths:
      - 'package.json'
      - 'package-lock.json'
      - '.github/copilot-config.json'

jobs:
  setup:
    name: Setup Development Environment
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Verify setup
        run: |
          echo "Node.js version: $(node -v)"
          echo "npm version: $(npm -v)"
      
      - name: Run tests
        run: npm run test
        
      - name: Lint code
        run: npm run lint
        
      - name: Check build
        run: npm run build