name: E2E Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'tests/**'
      - 'apps/web/**'
      - 'apps/api/**'
      - 'playwright.config.ts'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'tests/**'
      - 'apps/web/**'
      - 'apps/api/**'
      - 'playwright.config.ts'
      - 'package.json'
      - 'package-lock.json'

jobs:
  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: playaplan_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 22.x
      uses: actions/setup-node@v3
      with:
        node-version: 22.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx --yes playwright install --with-deps
    
    - name: Setup test environment
      run: |
        cp .env.sample .env
        # Add test-specific environment variables
        echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/playaplan_test" >> .env
        echo "JWT_SECRET=test-secret-key-for-ci" >> .env
        echo "NODE_ENV=test" >> .env
    
    - name: Setup database
      run: |
        cd apps/api
        npx --yes prisma migrate deploy
        npx --yes prisma db seed
    
    - name: Build applications
      run: |
        npm run build
    
    - name: Run Playwright tests
      run: npx --yes playwright test
      env:
        CI: true
    
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 10
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 10 